#!/bin/sh

make -C .. >/dev/null
make -C ../third_party/c-stringbuilder >/dev/null
mv ../libhb.a .
cc test.c -o test -I../include -L. -L../third_party/c-stringbuilder/ -ljq -lhb -lsb
./test
rm -f test libhb.a
make -C .. clean >/dev/null
make -C ../third_party/c-stringbuilder clean >/dev/null
